export const ImageSource = {
  Back: require('./Back.png'),
  Background: require('./Background.png'),
  Star: require('./Star.png'),
  IconSize: require('./IconSize.png'),
  Right: require('./Right.png'),
  FavouriteColor: require('./FavouriteColor.png'),
  FavouriteWhite: require('./FavouriteWhite.png'),
  LeftButton: require('./LeftButton.png'),
  RightButton: require('./RightButton.png'),
  Close: require('./Close.png'),
  Minus: require('./MinusIcon.png'),
  Plus: require('./PlusIcon.png'),
  BackgroundBtn: require('./BackgroundBtn.png'),
};
